### ISSUE TITLE
Transition logic

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#133]
In parts 2 and 3 the BB transitions automatically, the problem is that the transition block reads "Manual Trigger only" which is misleading because the Main loop has to have AP off to make it a manual transition (part plays back endlessly)

I think there should either be no text, or change to "Hold to Transition" when in this scenario.

That or use the main loop length input to say "Transition at m. X"
![Screenshot (41)](https://user-images.githubusercontent.com/62663388/94608887-12cbc600-026c-11eb-8417-4112c5653556.png)

**Comment by GoranRista** [comment]
It should definitely NOT say "hold for transition" since you don't need to hold for the transition. Transition fill is just a spare fill that can be utilized by user if they wish to, but the main sections transition regardless.
"Transition at measure" is confusing. If the section is supposed to play for 16 bars and there is no fill, what are you going to input in "transition at x bar"?
Do not change the text from it already is.
