### ISSUE TITLE
AP No outro song never ends

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#137]
Double tapping to stop an AP song with no outro fill never stops
using these songs, [Parts.zip](https://github.com/SingularSound/openbbm/files/5301817/Parts.zip), causes BB to never stop
![Screenshot (44)](https://user-images.githubusercontent.com/62663388/94617667-f9c91200-0277-11eb-9a5b-421d52b595ba.png)

**Comment by brennansingular** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/62663388/94619423-e3708580-027a-11eb-944a-6336cab7ba06.png)
Behavior changed once I changed the MIDI files

Now the song does end with a double tap

**Comment by JulissaDantes** [comment]
"causes BB to never stop" is this a BB bug or a BBM bug?

**Comment by GoranRista** [comment]
If the issue was gone once you changed the file @brennansingular , it is likely something to do with the type of a fill that was originally present. There could be a bug there relevant to some fills (like shorter than a full bar) or something that they contain. If you know what fill was used originally, that would possibly help.

**Comment by JulissaDantes** [comment]
Closed by #150
