### ISSUE TITLE
Change APBar shape

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#74]
Make the bar input boxes larger, so that there is more clearance between the numbers and the box. Making sure that two digits can be clearly seen and read. Make it rectangular, rather than square.

**Comment by JulissaDantes** [comment]
@Kiroto Please test this on the homonym branch.

**Comment by Kiroto** [comment]
After some testing, I have the following observations:
You can write anything on the boxes. Writing, for example '=2' instead of just '2' will make the AP stop working.
The boxes are too big; you can see 3-4 numbers, and you can write many more.

Thus, my suggestions are:
Disable the ability to write anything that isn't a number
Make the boxes a little smaller
Limit the characters to just 2 (so you can only write 2 numbers, nobody will probably go past 50 bars anyways)
